version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'RMQ'
    ports:
      - 5673:5672
      - 15673:15672
    
  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
     - 5432:5432
    env_file:
      - envs/.env.postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql

  redis: 
    image: redis:alpine
    container_name: 'redis'
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis:/var/lib/redis/data
    ports: 
      - 6379:6379
    env_file: 
     - envs/.env.redis
  
  calculator:
    container_name: 'exchange_calculator'
    image: exchange_calculator
    build: 
      # context: https://github.com/Kana-v1-exchange/calculator.git
      context: ../calculator
      dockerfile: Dockerfile
    env_file: 
     - envs/.env
  
  dashboard:
    container_name: 'exchnage_dashboard'
    image: exchange_dashboard
    build: 
      # context: https://github.com/Kana-v1-exchange/dashboard.git
      context: ../dashboard
      dockerfile: Dockerfile
    env_file: 
     - envs/.env
    ports:
     - 11111:11111
  
  frontend: 
    container_name: 'exchange_frontend'
    image: exchange_frontend
    build: 
      # context: https://github.com/Kana-v1-exchange/frontend.git
      context: ../frontend
      dockerfile: Dockerfile
    ports: 
     - 8080:8080

    
  
  # proxy:
  #   container_name: proxy
  #   build: proxy/
  #   ports:
  #    - 8000:8000

volumes:
  redis:
  postgresql:
