apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  namespace: exchange
data:
  master.conf: |
    maxmemory 100mb
    maxmemory-policy volatile-lru
    maxclients 10
    timeout 0
    appendonly no
    dbfilename redis_dumb.rdb
    requirepass REDIS_PASSWORD_to_change
    dir /data
  slave.conf: |
    maxmemory 100mb
    maxmemory-policy volatile-lru
    maxclients 10
    timeout 0
    appendonly no
    requirepass REDIS_PASSWORD_to_change
    dir /data


