apiVersion: v1
kind: Secret
metadata:
  name: exchange-secrets
  namespace: exchange
type: Opaque
data:
  REDIS_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_USER: cG9zdGdyZXM=
  RMQ_PASSWORD: WGxEaUlPRzgxZUU4STI3NTNzTFFkZ0ZHQlpDV2hZdk4=