apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: exchange
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 31234