apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: exchange
spec:
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: msolomodenko/exchange_calculator
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - secretRef:
              name: exchange-secrets
          - configMapRef:
              name: exchange-cm