apiVersion: v1
kind: Service
metadata:
  name: rmq-service
spec:
  selector:
    app: rmq
  type: LoadBalancer
  ports:
  - port: 5673
    targetPort: 5673
    nodePort: 31235
    protocol: TCP
    name: "msgs"
  - port: 15673
    targetPort: 15673
    nodePort: 31236
    protocol: TCP
    name: "ui"

